config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'questions#index'
  
  resources :questions do
  	member do
  		post :follow_topic 
  		post :follow_user
  	end 
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :following, foreign_key: :following_id, class_name: 'User'
	belongs_to :follower, foreign_key: :follower_id, class_name: 'User'

	validate :is_followed?, on: :create

	def is_followed?
		status = Follow.find_by(following_id: following_id).present?
		if status
			errors.add(:base, 'Already following')
		end
	end
end

app/models/follow_topic.rb
class FollowTopic < ApplicationRecord
	belongs_to :user

	validate :is_followed?, on: :create

	def is_followed?
		status = FollowTopic.find_by(user_id: user_id, topic_id: topic_id).present?
		if status
			errors.add(:base, 'Already following')
		end
	end
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers, dependent: :destroy
	belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  #Follow Relationships
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower, dependent: :destroy


  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following, dependent: :destroy


  #Question posted by the user
  has_many :questions, dependent: :destroy

  #Answers given by the user for a particular question
  has_many :answers, dependent: :destroy

  #User can follow the topic
  has_many :topics, class_name: 'FollowTopic', dependent: :destroy

  def follow(user_id, status)
    following_relationships.new(following_id: user_id, status: status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	before_action :authenticate_user!

	private

	def auth_member!
   		not_found unless authenticate_user!
    end

	def not_found
    	render plain: '404 Not Found', status: 404
  	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :auth_member!
	before_action :find_question, only: [:show, :follow_user, :follow_topic]

	def index
		@questions = Question.all.where.not(user_id: current_user).page(params[:page]).per(10)
	end

	def follow_user
		#Send 'true' for follow status by default
		following = current_user.follow(@question.user_id, true)
		if following.save
			redirect_to question_path, notice: 'Following successfully'
		else
			redirect_to question_path, notice: following.errors.full_messages.first
		end
	end

	def follow_topic
		following = current_user.topics.new(topic_id: @question.topic_id)
		if following.save
			redirect_to question_path, notice: 'Following successfully'
		else
			redirect_to question_path, notice: following.errors.full_messages.first
		end
	end

	private

	def find_question
		@question = Question.find_by(id: params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= alertify_flash %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<div class="container">
	<div class="row">
		<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
	</div>
	<div class="list-group">
		<%@questions.each do |ques|%>
		  	<%= link_to ques.content, question_path(ques.id), class:"list-group-item list-group-item-action question" %>
	  	<%end%>
	</div>
</div>

app/views/questions/show.html.erb
<div class="container">
	<p>
		Topic: <%=@question.topic.name%>
	</p>
	<p>
		Question: <%=@question.content%> 
	</p>
	<p>
	<%=link_to 'Follow User', follow_user_question_path(@question.id), method: :post, class: "btn btn-primary follow_user"%>
	<%=link_to 'Follow Topic', follow_topic_question_path(@question.id), method: :post, class: "btn btn-primary follow_topic"%>
	<p>
	<div class="list-group">
		Answers:
		<%@question.answers.each do |answer|%>
			<div class="list-group-item">
				<p class="answer"><%=answer.content%></p>
			</div>
		<%end%>
	</div>
</div>